Persistent loglevel
EdenGri/sonic-swss-common pull request #4
Opened 2022-09-12 11:05 UTC by EdenGri

2022-09-12 12:26 UTC, DavidZagury requested changes

2022-09-12 12:26 UTC, DavidZagury commented on common/logger.cpp
> +    auto table = std::make_shared<SubscriberStateTable>(&db, "LOGGER");
Can also be defined

2022-09-12 12:26 UTC, DavidZagury commented on tests/Makefile.am
> +                ../common/loglevel.cpp		\
Switch to spaces

2022-09-12 12:26 UTC, DavidZagury commented on common/loglevel.cpp
> +
Remove

2022-09-12 12:26 UTC, DavidZagury commented on tests/loglevel_ut.cpp
> +using namespace std;
Try to remove the using namespace

2022-09-13 11:15 UTC, dprital commented on common/loglevel.cpp
> +    SWSS_LOG_DEBUG("All components are with default loglevel");
Please fix this comment. It might be set to other value

2022-10-12 13:17 UTC, closed without merging